### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by justinesjw** [schienstockd/cecelia-doc#1]
Hi Dom, 

May I know how I can fix this error?

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for fastremap
Failed to build fastremap
ERROR: Could not build wheels for fastremap, which is required to install pyproject.toml-based projects
Error: Error installing package(s): "'numpy>=1.23.0'", "'blosc==1.11.1'", "jupyter", "'napari[all]'", "napari-animation", "h5py", "fsspec", "urllib3", "scikit-image", "requests", "'scanpy[leiden]'", "zarr", "dask", "ruamel.yaml", "tifffile", "btrack", "ome-types", "threadpoolctl", "'trimesh==3.23.5'", "rtree", "shapely", "pyopencl", "pandas", "cellpose", "anndata", "dask_image", "python-fcl", "stardist", "torch", "torchvision", "torchaudio", "leidenalg", "'squidpy>=1.3.0'", "SimpleITK", "skan", "pstree", "'efel<=5.2.5'", "pyclesperanto-prototype", "lxml", "sparse", "n2v", "'tensorflow<2.16'"
```

I followed the steps in your [installation page](https://cecelia.readthedocs.io/en/latest/installation.html) and failed here 
`reticulate::install_miniconda()`
so I ran 
`cciaCondaCreate(preinstallNapari = TRUE)` but it gave me an error of `Failed to build fastremap` 

This is my session info
<img width="1031" alt="image" src="https://github.com/schienstockd/cecelia-doc/assets/26448066/7e8b3b60-86dd-4159-8c2d-8ae1a0f83b0d">

Thank you for reading through my issue! 

Best, 
Justine

**Comment by schienstockd** [comment]
OK - I haven't seen this before. The conda environment should be there, I think.
Can you try install [`fastremap`](https://pypi.org/project/fastremap/) manually? See if that works and then run the R-code again?

```bash
conda activate r-cecelia-env
pip install fastremap
```

Otherwise, you can check this [`issue`](https://github.com/seung-lab/fastremap/issues/38) and try install from source
```bash
pip install fastremap==1.14.2 --no-binary :all: --force-reinstall
```

You might need [Xcode](https://developer.apple.com/xcode/).

**Comment by justinesjw** [comment]
Thanks! But neither of those works for me. 

I tried building the wheel file myself, downloaded from [this page](https://www.wheelodex.org/projects/fastremap/wheels/fastremap-1.14.2-cp39-cp39-macosx_11_0_arm64.whl/), but interestingly it cannot build using python from the environment 

<img width="452" alt="image" src="https://github.com/schienstockd/cecelia-doc/assets/26448066/a00c02c0-61dd-4ebc-a015-b3b6effe2fbf">

but it works with my base python 

<img width="452" alt="image" src="https://github.com/schienstockd/cecelia-doc/assets/26448066/56eab55a-04e1-466d-bc31-aaf9a2f6493b">

<img width="452" alt="image" src="https://github.com/schienstockd/cecelia-doc/assets/26448066/7f797516-3dff-4535-b3ab-a430d8af17f0">

Do you have any idea how to solve this?

**Comment by schienstockd** [comment]
What is the output of this?

```bash
pip install numpy
pip install fastremap --no-binary :all:
```

**Comment by schienstockd** [comment]
Could you also try to update pip in the conda environment?

```bash
pip install --upgrade pip
```

**Comment by justinesjw** [comment]
Here is the output for this 
> What is the output of this?
> 
> ```shell
> pip install numpy
> pip install fastremap --no-binary :all:
> ```

<img width="872" alt="image" src="https://github.com/user-attachments/assets/3ae23656-5b3f-4ae8-81ce-536e4a56e2c9">

And I've tried 
`pip install --upgrade pip`

and also I've tried with `pip3`

**Comment by schienstockd** [comment]
So it worked? At least the wheel was built ok.

**Comment by justinesjw** [comment]
ah! sorry.. I forgot to attach the last part of the output 

<img width="869" alt="image" src="https://github.com/user-attachments/assets/f68af57c-e4ff-4600-a9c3-1a313ee5282d">

The previous image is to show that `numpy` is installed

**Comment by justinesjw** [comment]
Is it possible to specify which python to use here? `cciaCondaCreate(envType = "image")`

**Comment by schienstockd** [comment]
There is only one python in the conda environment - can you do `pip freeze` and paste the output?

**Comment by schienstockd** [comment]
`pip install fastremap==1.13` does this work?

**Comment by justinesjw** [comment]
YESS!! 

Thank you!!!
