### ISSUE TITLE
Error with cciaModels()

### ISSUE THREAD

**Issue by justinesjw** [schienstockd/cecelia-doc#2]
Hi Dom, 

May I know how can I solve this error?

<img width="828" alt="image" src="https://github.com/user-attachments/assets/9b8ff32d-6407-451a-94c2-3506b68e8505">

Thanks! 
Justine

**Comment by schienstockd** [comment]
What did you do before that? You need to initialise the path that you used for `cciaSetup("/REPLACE/WITH/YOUR/PATH")`. Can you try the following and replace your path in `cciaUse`:

```R
library(flowCore)
Sys.setenv(KMP_DUPLICATE_LIB_OK = "TRUE")
library(cecelia)
cciaUse("/REPLACE/WITH/YOUR/PATH")
cciaModels()
```
